#CI项目
name: QCA-ALL

#CI计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}-${{matrix.PROFILE}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES, RIVWRT_AX6600]
        PROFILE: [PURE, PLUS]
        SOURCE: [ones20250/immortalwrt_ipq]
        BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_THEME: bootstrap

      # RivWRT 默认信息
      # 基于 PurpleRed-River/Openwrt-AX6600
      # 上游来源 ones20250/Openwrt-AX6600
      WRT_NAME: RivWRT
      WRT_SSID: RivWRT
      WRT_WORD: 1qaz!QAZ
      WRT_IP: 192.168.100.1

      # 默认密码提示
      WRT_PW: 无

      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      WRT_BRANCH: ${{matrix.BRANCH}}
      WRT_SOURCE: ${{matrix.SOURCE}}
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_PROFILE: ${{matrix.PROFILE}}
      WRT_TEST: ${{inputs.TEST}}
